### ISSUE TITLE
Only 4 Decimal Places

### ISSUE THREAD

**Issue by metal450** [LedgerHQ/ledger-live#553]
**Describe the bug**

This is a re-post of this original issue from the prior repo: https://github.com/LedgerHQ/ledger-live-desktop/issues/4896

Ledger Live is only showing 4 digits of precision for all assets - Bitcoin, Ethereum, etc. This makes it more or less unusable if you want to have any measure of accuracy in your accounting.

Tested on 2.43.1 on Win10

**Expected behavior**

The app should show the actual proper balances (i.e. all 8 digits for Bitcoin). Or if some users don't wish to know their actual holdings (?), at least make it optional.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by Kansai53** [comment]
Agree - this seems to be a regression in one of the recent versions, as it definitely displayed proper balances before.

Hopefully they can fix this soon, so I can avoid needing to rollback to the previous/working version & import all my accounts again from scratch.

**Comment by Drkmstr310** [comment]
Also having this problem, balance are no accurate any more, only rough estimates. How to fix?

**Comment by Steuberke** [comment]
I will follow this topic because its really annoying that Ledger Live doesn't show 8 decimals. They should make a setting where you can choose how many decimals you would like to see. @bouchepat mentioned this before in topic -> https://github.com/LedgerHQ/ledger-live-desktop/issues/4896

**Comment by Thomas20232030** [comment]
It is annoying and it should really be changed soon. Is there any workaraound for this with other tools concerning bitcoin?

**Comment by metal450** [comment]
Help box on the lower right of https://support.ledger.com

**Comment by Steuberke** [comment]
> Help box on the lower right of https://support.ledger.com

I did my job and asked more people to do the same.

**Comment by metal450** [comment]
Was this actually completed, or did it just get closed because Ledger didn't bother to respond?  I've not been able to update to verify, due to this other breaking change: https://github.com/LedgerHQ/ledger-live/issues/1005

**Comment by gre** [comment]
Sorry for this auto close, the topic is still relevant, we've been reviewing this topic a few days actually, still waiting for some people to chose the direction on the topic ( which was last changed in https://github.com/LedgerHQ/ledger-live-desktop/commit/2c863861f0e7b9d5eeb7710d2f600fb065b70f71 ), we'll get back to you / document the choices 🙏

**Comment by metal450** [comment]
Still not fixed as far as I know, but I'm not able to verify (as new versions of Ledger Live remain broken due to https://github.com/LedgerHQ/ledger-live/issues/1005 - thus I remain stuck on 2.43.1).

**Comment by Al-cm** [comment]
Running Ledger Live version 2.47.0 on Win 11 Pro, and the issue is still not fixed.

**Comment by Thomas20232030** [comment]
I am really not happy with this situation. Concerning Bitcoin and the underlying sats four digits are really not enogh!

 

When onboarding new members to the cryptospace these missing four digits are important…

 

Thomas

 

Von: Al-cm ***@***.***> 
Gesendet: Montag, 26. September 2022 09:12
An: LedgerHQ/ledger-live ***@***.***>
Cc: Thomas Hoppe ***@***.***>; Comment ***@***.***>
Betreff: Re: [LedgerHQ/ledger-live] Only 4 Decimal Places (Issue #553)

 

Running Ledger Live version 2.47.0 on Win 11 Pro, and the issue is still not fixed.

**Comment by Steuberke** [comment]
Same. Takes to long to fix. There was a support AMA few weeks ago. Brought the issue in the stream as well and they did admit this was an issue. Still no fix after months. If they don't fix this I'll move to another hardware wallet. 

Really really disappointed at Ledger for this and still no clarification from their side.

**Comment by Kansai53** [comment]
2.49 was released and this is *STILL* broken. It's been more than half a year. Has everyone given up & just moved to Trezor yet? I'm about ready to throw out my Ledgers and start over, what kind of company is this that can't even show you your actual balances...

**Comment by metal450** [comment]
Still broken in 2.49.2

**Comment by LeadManPL** [comment]
Confirming it is broken in  ledger-live-desktop-2.49.2-linux-x86_64.AppImage 
The same case on Android version 3.10.0 (66463)
Its been 5 months already and this issue is not even assigned to no one?

**Comment by Thomas20232030** [comment]
I would be happy if this can be fixed in this year....

**Comment by nparigi-ledger** [comment]
Should be resolved in this PR, increasing in Live mobile and desktop the number of digits, and even more precise in Account pages

**Comment by Thomas20232030** [comment]
This would really be great!

**Comment by Steuberke** [comment]
I just had a update of Ledger Live (desktop) to version 2.50.1 and still shows not enough decimals.

**Comment by Thomas20232030** [comment]
Yes, I can see it. Let´s hope for the near future and for the next version....

**Comment by etc** [comment]
Yes, still broken in 2.50.1. Absolutely incredible to regress in this way and then take so long to revert it.

**Comment by elbywan** [comment]
We understand the frustration, but:
- we do not accept feature or bug requests regarding the Ledger Live applications on Github: https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#disclaimer 
- this is not the right place to rant or post non-constructive comments

As @nparigi-ledger said ealier we have a pending pull request handling the problem and the fix will get in production in the near future.
