### ISSUE TITLE
[Bug]: Unable to resolve module @ledgerhq/domain-service/signers/index

### ISSUE THREAD

**Issue by iGroza** [LedgerHQ/ledger-live#6173]
### Impacted Library name

@ledgerhq/hw-app-eth

### Impacted Library version

6.35.4

### Describe the bug

Error durning initialisation:

```js
Error: Unable to resolve module @ledgerhq/domain-service/signers/index from /Users/..../node_modules/@ledgerhq/hw-app-eth/lib/services/ledger/index.js: @ledgerhq/domain-service/signers/index could not be found within the project or in these directories:
  node_modules
  13 | const logs_1 = require("@ledgerhq/logs");
  14 | const abi_1 = require("@ethersproject/abi");
> 15 | const index_1 = require("@ledgerhq/domain-service/signers/index");
     |                          ^
  16 | const erc20_1 = require("./erc20");
  17 | const contracts_1 = require("./contracts");
  18 | const nfts_1 = require("./nfts");
 ```

### Expected behavior

initialisation without error

### Additional context

```json
"dependencies": {
  "@ledgerhq/hw-app-eth": "6.35.4",
  "@ledgerhq/hw-transport": "6.30.3",
  "@ledgerhq/react-native-hw-transport-ble": "6.32.2"
 }
 ```

**Comment by bobo2018cp** [comment]
I have same problem,

**Comment by bobo2018cp** [comment]
<img width="642" alt="image" src="https://github.com/LedgerHQ/ledger-live/assets/46776533/4eee4734-2fef-46d1-8f09-cbc00d6d5edc">
I have the same problem!

**Comment by iGroza** [comment]
Fixed by adding custom `resolveRequest` inside my `metro.config.js` config.

```js
const path = require("path");
const { getDefaultConfig, mergeConfig } = require('@react-native/metro-config');
const defaultModuleResolver = getDefaultConfig(__dirname).resolver.resolveRequest;

const config = {
  // your other option here
  // ...
  resolver: {
    resolveRequest: (context, moduleName, platform) => {
      try {
        return context.resolveRequest(context, moduleName, platform);
      } catch (error) {
        console.warn('\n1️⃣ context.resolveRequest cannot resolve: ', moduleName);
      }

      try {
        const resolution = require.resolve(moduleName, {
          paths: [path.dirname(context.originModulePath), ...config.resolver.nodeModulesPaths],
        });

        if (path.isAbsolute(resolution)) {
          return {
            filePath: resolution,
            type: "sourceFile",
          };
        }
      } catch (error) {
        console.warn('\n2️⃣ require.resolve cannot resolve: ', moduleName);
      }

      try {
        return defaultModuleResolver(context, moduleName, platform);
      } catch (error) {
        console.warn('\n3️⃣ defaultModuleResolver cannot resolve: ', moduleName);
      }

      try {
        return {
          filePath: require.resolve(moduleName),
          type: "sourceFile",
        };
      } catch (error) {
        console.warn('\n4️⃣ require.resolve cannot resolve: ', moduleName);
      }

      try {
        const resolution = getDefaultConfig(require.resolve(moduleName)).resolver?.resolveRequest
        return resolution(context, moduleName, platform);
      } catch (error) {
        console.warn('\n5️⃣ getDefaultConfig cannot resolve: ', moduleName);
      }
    },
  },
};

module.exports = mergeConfig(getDefaultConfig(__dirname), config);

```

**Comment by bobo2018cp** [comment]
<img width="926" alt="image" src="https://github.com/LedgerHQ/ledger-live/assets/46776533/402143e6-d9ed-4738-9879-fd59632d98d6">
"I followed the configuration steps and obtained this result."

**Comment by KVNLS** [comment]
Hello @iGroza, where do you have this error, please? Directly on Ledger Live or on another project?
Currently, we have issues with symlinks + React Native, this is solved on the latest react native version 0.73 (https://reactnative.dev/blog/2023/12/06/0.73-debugging-improvements-stable-symlinks#stable-symlink-support-in-metro) I'm working on the upgrade here https://github.com/LedgerHQ/ledger-live/pull/6596 and it works well.
Moreover, we don't export correctly our modules if you look at the package.json of @ledgerhq/domain-service. I would not recommend adding a custom resolver by yourself as it can lead to issues upgrading to a new version and maintaining it.
If you are trying to consume this module in another project I think that we could provide a fix by explicitly exporting this module in the package.json.

**Comment by enero-o** [comment]
Hello @KVNLS , I still have this same issue: failed imports of `@ledgerhq/evm-tools/selectors/index` and `@ledgerhq/domain-service/signers/index`.  Both of which are being used by `@xhainjs/evm`.

Here is the current error log output

```
Error: Unable to resolve module @ledgerhq/evm-tools/selectors/index from /app/node_modules/@xchainjs/xchain-evm/node_modules/@ledgerhq/hw-app-eth/lib/utils.js: @ledgerhq/evm-tools/selectors/index could not be found within the project or in these directories:
  node_modules/@xchainjs/xchain-evm/node_modules
  node_modules
  3 | exports.mergeResolutions = exports.nftSelectors = exports.tokenSelectors = exports.intAsHexBytes = exports.decodeTxInfo = exports.maybeHexBuffer = exports.hexBuffer = exports.splitPath = exports.padHexString = exports.ERC1155_CLEAR_SIGNED_SELECTORS = exports.ERC721_CLEAR_SIGNED_SELECTORS = exports.ERC20_CLEAR_SIGNED_SELECTORS = void 0;
  4 | const bignumber_js_1 = require("bignumber.js");
> 5 | const index_1 = require("@ledgerhq/evm-tools/selectors/index");
    |                          ^
  6 | Object.defineProperty(exports, "ERC20_CLEAR_SIGNED_SELECTORS", { enumerable: true, get: function () { return index_1.ERC20_CLEAR_SIGNED_SELECTORS; } });
  7 | Object.defineProperty(exports, "ERC721_CLEAR_SIGNED_SELECTORS", { enumerable: true, get: function () { return index_1.ERC721_CLEAR_SIGNED_SELECTORS; } });
  8 | Object.defineProperty(exports, "ERC1155_CLEAR_SIGNED_SELECTORS", { enumerable: true, get: function () { return index_1.ERC1155_CLEAR_SIGNED_SELECTORS; } });
    at ModuleResolver.resolveDependency (/app/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:150:15)
    
```

Looks like the signer and selector modules have not been exported properly, 

Metro - 0.81.4
React-Native - 0.76.5
